### ISSUE TITLE
Missing Sileo?

### ISSUE THREAD

**Issue by Macleykun** [ramenrepo/limelight#2]
Hey hello!

I've been using your icons from the moment i jailbreaked my older and newer devices, but i happen to notice the Sileo icon:
![image](https://user-images.githubusercontent.com/26381427/57870722-f7435500-7807-11e9-8ba9-b4223e26dd66.png)
Isn't in the limelight i downloaded from your repo, i tried everything but still haven't been able to find that one. I use version 1.9.6.

I love your work and hope your able to help me out on this little issue.

**Comment by Macleykun** [comment]
@ramenrepo @itskvad um, any help 😅

**Comment by Macleykun** [comment]
Um hello? @ramenrepo

**Comment by itskvad** [comment]
Hi!
There's no Sileo icon in this repo. 
Do you have access to hi res version? 
Can you do a PR? If not I can do one. 
Thanks

**Comment by Macleykun** [comment]
I sadly don't have the icon ether, i only saw it on the preview of the package and the github repo here.
I don't know why this icon is shown but not released yet.

**Comment by Macleykun** [comment]
Um... anyone? Is this no longer updated or...?

**Comment by itskvad** [comment]
/me is not a designer :( 
Will look to add the funky Apollo icon I saw on Reddit a couple of days ago though.

**Comment by Macleykun** [comment]
oh ok! thank you so much!
